import type {
  ModeratorNotification,
  ModeratorProfile,
  ModeratorShift,
  OrgInboxThread,
  OrgShiftLog,
} from "@/lib/types/moderator";

/** Logged-in persona for the mock org portal. */
export const currentModerator: ModeratorProfile = {
  id: "mod_parks",
  name: "Elena Vasquez",
  avatar:
    "https://api.dicebear.com/9.x/avataaars/svg?seed=Elena&backgroundColor=DDF0FB",
  roleTitle: "Parks Volunteer Coordinator",
  totalVerifications: 214,
  orgId: "org_city_parks",
  orgName: "City Parks Dept.",
  orgAvatar:
    "https://api.dicebear.com/9.x/icons/svg?seed=ParksOrg&backgroundColor=DDF0FB",
};

/** Micro-level persona: staffs only the Riverside cleanup shift. */
export const microModerator: ModeratorProfile = {
  id: "mod_parks_riverside",
  name: "Dana Whitfield",
  avatar:
    "https://api.dicebear.com/9.x/avataaars/svg?seed=Dana&backgroundColor=FBE4F1",
  roleTitle: "Riverside Shift Lead",
  totalVerifications: 12,
  orgId: "org_city_parks",
  orgName: "City Parks Dept.",
  orgAvatar:
    "https://api.dicebear.com/9.x/icons/svg?seed=ParksOrg&backgroundColor=DDF0FB",
};

/** Lookup for session → display persona (topbar, sidebar, greetings). */
export const moderatorProfiles: Record<string, ModeratorProfile> = {
  [currentModerator.id]: currentModerator,
  [microModerator.id]: microModerator,
};

/**
 * City Parks shifts as the org sees them. `shift_riverside_cleanup` is the
 * same id the student portal uses, so its QR session is scannable from the
 * student side. The rest are org-only and never appear in the student feed.
 */
export const moderatorShifts: ModeratorShift[] = [
  {
    id: "shift_riverside_cleanup",
    title: "Riverside Park Cleanup & Tree Planting",
    description:
      "Restore Riverside Park trails, remove invasive plants, and plant native trees.",
    category: "Environment",
    categoryKey: "environment",
    categoryTint: "sky",
    date: "Sat, Jun 14 · 9:00 AM",
    scheduledAt: "2026-06-14T13:00:00.000Z",
    slots: 12,
    committedCount: 8,
    checkedInCount: 0,
    hours: 4,
    location: "Riverside Park, 1200 River Rd",
    img: "https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=600&q=70",
    status: "upcoming",
  },
  {
    id: "shift_parks_native_garden",
    title: "Native Pollinator Garden Build",
    description:
      "Lay out beds and plant native wildflowers at the Westside greenway.",
    category: "Environment",
    categoryKey: "environment",
    categoryTint: "sky",
    date: "Sun, Jun 22 · 10:00 AM",
    scheduledAt: "2026-06-22T14:00:00.000Z",
    slots: 10,
    committedCount: 4,
    checkedInCount: 0,
    hours: 3,
    location: "Westside Greenway, 340 Meadow Ln",
    img: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&q=70",
    status: "upcoming",
  },
  {
    id: "shift_parks_trail_may",
    title: "Trail Restoration Day",
    description:
      "Rebuild washed-out trail sections and clear drainage channels.",
    category: "Environment",
    categoryKey: "environment",
    categoryTint: "sky",
    date: "Sat, May 24 · 9:00 AM",
    scheduledAt: "2026-05-24T13:00:00.000Z",
    slots: 14,
    committedCount: 14,
    checkedInCount: 11,
    hours: 3,
    location: "Riverside Park, North Trailhead",
    img: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=600&q=70",
    status: "completed",
  },
  {
    id: "shift_parks_mulch_apr",
    title: "Playground Mulch & Litter Sweep",
    description:
      "Mulch playground beds and run a litter sweep across the east lawn.",
    category: "Environment",
    categoryKey: "environment",
    categoryTint: "sky",
    date: "Sat, Apr 12 · 9:00 AM",
    scheduledAt: "2026-04-12T13:00:00.000Z",
    slots: 12,
    committedCount: 10,
    checkedInCount: 9,
    hours: 3,
    location: "Riverside Park, East Lawn",
    img: "https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=600&q=70",
    status: "completed",
  },
];

export function getModeratorShiftById(
  id: string,
): ModeratorShift | undefined {
  return moderatorShifts.find((shift) => shift.id === id);
}

function studentAvatar(seed: string, bg: string): string {
  return `https://api.dicebear.com/9.x/avataaars/svg?seed=${seed}&backgroundColor=${bg}`;
}

/**
 * Hours claims submitted to City Parks. Pending rows are manual claims
 * (students who missed the QR scan); flagged rows reproduce the fraud rule:
 * 3+ students logging identical unverified hours within 10 minutes.
 */
export const orgShiftLogs: OrgShiftLog[] = [
  {
    id: "orglog_maya_jun7",
    shiftId: "shift_riverside_cleanup",
    shiftTitle: "Riverside Park Cleanup & Tree Planting",
    studentId: "user_maya_chen",
    studentName: "Maya Chen",
    studentAvatar: studentAvatar("Maya", "ECEAFB"),
    school: "Lincoln High",
    category: "Environment",
    categoryKey: "environment",
    categoryTint: "sky",
    date: "Jun 7, 2026",
    completedAt: "2026-06-07T17:00:00.000Z",
    hours: 4,
    status: "pending",
    method: "manual",
    verifiedAt: null,
    studentLogId: "log_riverside_pending",
  },
  {
    id: "orglog_aisha_jun7",
    shiftId: "shift_parks_trail_may",
    shiftTitle: "Trail Restoration Day",
    studentId: "user_aisha_thompson",
    studentName: "Aisha Thompson",
    studentAvatar: studentAvatar("Aisha", "FBE4F1"),
    school: "Lincoln High",
    category: "Environment",
    categoryKey: "environment",
    categoryTint: "sky",
    date: "Jun 7, 2026",
    completedAt: "2026-06-07T17:10:00.000Z",
    hours: 3.5,
    status: "pending",
    method: "manual",
    verifiedAt: null,
  },
  {
    id: "orglog_leo_jun7",
    shiftId: "shift_parks_trail_may",
    shiftTitle: "Trail Restoration Day",
    studentId: "user_leo_martinez",
    studentName: "Leo Martinez",
    studentAvatar: studentAvatar("Leo", "DDF0FB"),
    school: "Westview High",
    category: "Environment",
    categoryKey: "environment",
    categoryTint: "sky",
    date: "Jun 7, 2026",
    completedAt: "2026-06-07T17:25:00.000Z",
    hours: 4,
    status: "pending",
    method: "manual",
    verifiedAt: null,
  },
  {
    id: "orglog_hannah_may24",
    shiftId: "shift_parks_trail_may",
    shiftTitle: "Trail Restoration Day",
    studentId: "user_hannah_cho",
    studentName: "Hannah Cho",
    studentAvatar: studentAvatar("Hannah", "ECEAFB"),
    school: "Lincoln High",
    category: "Environment",
    categoryKey: "environment",
    categoryTint: "sky",
    date: "May 24, 2026",
    completedAt: "2026-05-24T16:40:00.000Z",
    hours: 2.5,
    status: "pending",
    method: "manual",
    verifiedAt: null,
  },
  {
    id: "orglog_jordan_apr12",
    shiftId: "shift_parks_mulch_apr",
    shiftTitle: "Playground Mulch & Litter Sweep",
    studentId: "friend_jordan",
    studentName: "Jordan Park",
    studentAvatar: studentAvatar("Jordan", "DDF0FB"),
    school: "Lincoln High",
    category: "Environment",
    categoryKey: "environment",
    categoryTint: "sky",
    date: "Apr 12, 2026",
    completedAt: "2026-04-12T16:02:00.000Z",
    hours: 3,
    status: "flagged",
    method: "manual",
    verifiedAt: null,
    flagReason:
      "3 students logged identical unverified hours within 10 minutes. Held for review per school policy.",
  },
  {
    id: "orglog_sofia_apr12",
    shiftId: "shift_parks_mulch_apr",
    shiftTitle: "Playground Mulch & Litter Sweep",
    studentId: "friend_sofia",
    studentName: "Sofia Reyes",
    studentAvatar: studentAvatar("Sofia", "FBE4F1"),
    school: "Lincoln High",
    category: "Environment",
    categoryKey: "environment",
    categoryTint: "sky",
    date: "Apr 12, 2026",
    completedAt: "2026-04-12T16:06:00.000Z",
    hours: 3,
    status: "flagged",
    method: "manual",
    verifiedAt: null,
    flagReason:
      "3 students logged identical unverified hours within 10 minutes. Held for review per school policy.",
  },
  {
    id: "orglog_devin_apr12",
    shiftId: "shift_parks_mulch_apr",
    shiftTitle: "Playground Mulch & Litter Sweep",
    studentId: "friend_devin",
    studentName: "Devin Walters",
    studentAvatar: studentAvatar("Devin", "ECEAFB"),
    school: "Lincoln High",
    category: "Environment",
    categoryKey: "environment",
    categoryTint: "sky",
    date: "Apr 12, 2026",
    completedAt: "2026-04-12T16:09:00.000Z",
    hours: 3,
    status: "flagged",
    method: "manual",
    verifiedAt: null,
    flagReason:
      "3 students logged identical unverified hours within 10 minutes. Held for review per school policy.",
  },
  {
    id: "orglog_maya_may24",
    shiftId: "shift_parks_trail_may",
    shiftTitle: "Trail Restoration Day",
    studentId: "user_maya_chen",
    studentName: "Maya Chen",
    studentAvatar: studentAvatar("Maya", "ECEAFB"),
    school: "Lincoln High",
    category: "Environment",
    categoryKey: "environment",
    categoryTint: "sky",
    date: "May 24, 2026",
    completedAt: "2026-05-24T14:00:00.000Z",
    hours: 3,
    status: "verified",
    method: "qr",
    verifiedAt: "2026-05-24T15:00:00.000Z",
    verifiedByModeratorId: "mod_parks",
    studentLogId: "log_parks_may24",
  },
  {
    id: "orglog_marcus_may24",
    shiftId: "shift_parks_trail_may",
    shiftTitle: "Trail Restoration Day",
    studentId: "user_marcus_bell",
    studentName: "Marcus Bell",
    studentAvatar: studentAvatar("MarcusB", "DDF0FB"),
    school: "Westview High",
    category: "Environment",
    categoryKey: "environment",
    categoryTint: "sky",
    date: "May 24, 2026",
    completedAt: "2026-05-24T14:05:00.000Z",
    hours: 3,
    status: "verified",
    method: "qr",
    verifiedAt: "2026-05-24T15:02:00.000Z",
    verifiedByModeratorId: "mod_parks",
  },
  {
    id: "orglog_aisha_apr12",
    shiftId: "shift_parks_mulch_apr",
    shiftTitle: "Playground Mulch & Litter Sweep",
    studentId: "user_aisha_thompson",
    studentName: "Aisha Thompson",
    studentAvatar: studentAvatar("Aisha", "FBE4F1"),
    school: "Lincoln High",
    category: "Environment",
    categoryKey: "environment",
    categoryTint: "sky",
    date: "Apr 12, 2026",
    completedAt: "2026-04-12T13:30:00.000Z",
    hours: 3,
    status: "verified",
    method: "qr",
    verifiedAt: "2026-04-12T14:10:00.000Z",
    verifiedByModeratorId: "mod_parks",
  },
  {
    id: "orglog_leo_apr12",
    shiftId: "shift_parks_mulch_apr",
    shiftTitle: "Playground Mulch & Litter Sweep",
    studentId: "user_leo_martinez",
    studentName: "Leo Martinez",
    studentAvatar: studentAvatar("Leo", "DDF0FB"),
    school: "Westview High",
    category: "Environment",
    categoryKey: "environment",
    categoryTint: "sky",
    date: "Apr 12, 2026",
    completedAt: "2026-04-12T13:32:00.000Z",
    hours: 3,
    status: "verified",
    method: "qr",
    verifiedAt: "2026-04-12T14:12:00.000Z",
    verifiedByModeratorId: "mod_parks",
  },
  {
    id: "orglog_hannah_apr12",
    shiftId: "shift_parks_mulch_apr",
    shiftTitle: "Playground Mulch & Litter Sweep",
    studentId: "user_hannah_cho",
    studentName: "Hannah Cho",
    studentAvatar: studentAvatar("Hannah", "ECEAFB"),
    school: "Lincoln High",
    category: "Environment",
    categoryKey: "environment",
    categoryTint: "sky",
    date: "Apr 12, 2026",
    completedAt: "2026-04-12T13:45:00.000Z",
    hours: 2.5,
    status: "rejected",
    method: "manual",
    verifiedAt: null,
    rejectReason: "No check-in record found for this shift date.",
  },
];

/** Seed alerts mirroring the pending/flagged queue and unread threads. */
export const moderatorNotifications: ModeratorNotification[] = [
  {
    id: "modnotif_flagged_apr12",
    kind: "claim_flagged",
    title: "3 claims held by fraud check",
    body: "Jordan Park, Sofia Reyes, and Devin Walters logged identical hours within 10 minutes at Playground Mulch & Litter Sweep.",
    createdAt: "2026-04-12T16:15:00.000Z",
    read: false,
    href: "/moderator/verifications?status=flagged",
  },
  {
    id: "modnotif_pending_maya",
    kind: "claim_pending",
    title: "Maya Chen submitted 4 hrs",
    body: "Manual claim for Trail Restoration Day is waiting for your review.",
    createdAt: "2026-06-07T17:00:00.000Z",
    read: false,
    href: "/moderator/verifications/orglog_maya_jun7",
  },
  {
    id: "modnotif_pending_aisha",
    kind: "claim_pending",
    title: "Aisha Thompson submitted 3.5 hrs",
    body: "Manual claim for Trail Restoration Day is waiting for your review.",
    createdAt: "2026-06-07T17:10:00.000Z",
    read: false,
    href: "/moderator/verifications/orglog_aisha_jun7",
  },
  {
    id: "modnotif_msg_maya",
    kind: "message_received",
    title: "New message from Maya Chen",
    body: "Should I bring gloves, or will those be provided?",
    createdAt: "2026-06-10T14:22:00.000Z",
    read: false,
    href: "/moderator/messages?thread=org_thread_maya_riverside",
  },
  {
    id: "modnotif_msg_aisha",
    kind: "message_received",
    title: "New message from Aisha Thompson",
    body: "I missed the QR scan at trail day. Can you verify my hours manually?",
    createdAt: "2026-06-07T17:12:00.000Z",
    read: true,
    href: "/moderator/messages?thread=org_thread_aisha_trail",
  },
];

export const moderatorMessageTemplates = [
  "Thanks for volunteering — see you at the shift.",
  "Check-in code will be displayed when you arrive.",
  "I reviewed your hours and approved them.",
  "Please bring closed-toe shoes and a water bottle.",
];

/** Student threads scoped to City Parks shifts Elena moderates. */
export const orgInboxThreads: OrgInboxThread[] = [
  {
    id: "org_thread_maya_riverside",
    studentId: "user_maya_chen",
    studentName: "Maya Chen",
    studentAvatar: studentAvatar("Maya", "ECEAFB"),
    school: "Lincoln High",
    shiftId: "shift_riverside_cleanup",
    shiftTitle: "Riverside Park Cleanup & Tree Planting",
    shiftDate: "Sat, Jun 14 · 9:00 AM",
    unread: true,
    messages: [
      {
        id: "org_msg_maya_1",
        sender: "moderator",
        body: "Reminder: wear closed-toe shoes and bring a water bottle.",
        sentAt: "2026-06-06T18:00:00.000Z",
      },
      {
        id: "org_msg_maya_2",
        sender: "student",
        body: "Should I bring gloves, or will those be provided?",
        sentAt: "2026-06-10T14:22:00.000Z",
      },
    ],
    updatedAt: "2026-06-10T14:22:00.000Z",
  },
  {
    id: "org_thread_aisha_trail",
    studentId: "user_aisha_thompson",
    studentName: "Aisha Thompson",
    studentAvatar: studentAvatar("Aisha", "FBE4F1"),
    school: "Lincoln High",
    shiftId: "shift_parks_trail_may",
    shiftTitle: "Trail Restoration Day",
    shiftDate: "Sat, May 24 · 9:00 AM",
    unread: true,
    messages: [
      {
        id: "org_msg_aisha_1",
        sender: "student",
        body: "I missed the QR scan at trail day. Can you verify my hours manually?",
        sentAt: "2026-06-07T17:12:00.000Z",
      },
    ],
    updatedAt: "2026-06-07T17:12:00.000Z",
  },
  {
    id: "org_thread_leo_garden",
    studentId: "user_leo_martinez",
    studentName: "Leo Martinez",
    studentAvatar: studentAvatar("Leo", "DDF0FB"),
    school: "Westview High",
    shiftId: "shift_parks_native_garden",
    shiftTitle: "Native Pollinator Garden Build",
    shiftDate: "Sun, Jun 22 · 10:00 AM",
    unread: false,
    messages: [
      {
        id: "org_msg_leo_1",
        sender: "student",
        body: "Is parking available at the Westside greenway entrance?",
        sentAt: "2026-06-09T11:05:00.000Z",
      },
      {
        id: "org_msg_leo_2",
        sender: "moderator",
        body: "Yes — use the lot off Meadow Ln. Street parking works too.",
        sentAt: "2026-06-09T11:18:00.000Z",
      },
    ],
    updatedAt: "2026-06-09T11:18:00.000Z",
  },
  {
    id: "org_thread_marcus_trail",
    studentId: "user_marcus_bell",
    studentName: "Marcus Bell",
    studentAvatar: studentAvatar("MarcusB", "DDF0FB"),
    school: "Westview High",
    shiftId: "shift_parks_trail_may",
    shiftTitle: "Trail Restoration Day",
    shiftDate: "Sat, May 24 · 9:00 AM",
    unread: false,
    messages: [
      {
        id: "org_msg_marcus_1",
        sender: "moderator",
        body: "Thanks for a great shift — your hours are verified.",
        sentAt: "2026-05-24T15:10:00.000Z",
      },
      {
        id: "org_msg_marcus_2",
        sender: "student",
        body: "Appreciate it. Happy to help on the next trail day.",
        sentAt: "2026-05-24T16:02:00.000Z",
      },
    ],
    updatedAt: "2026-05-24T16:02:00.000Z",
  },
];
