import type {
  CategoryProgress,
  Friend,
  MonthlyHours,
  Organization,
  Shift,
  ShiftLog,
  StudentProfile,
  TintKey,
} from "@/lib/types/student";

export type { CategoryKey, LogStatus, TintKey } from "@/lib/types/student";

export const student: StudentProfile = {
  id: "user_maya_chen",
  name: "Maya Chen",
  firstName: "Maya",
  grade: "11th Grade · Lincoln High",
  avatar:
    "https://api.dicebear.com/9.x/avataaars/svg?seed=Maya&backgroundColor=ECEAFB",
  schoolId: "school_lincoln_high",
  schoolState: "FL",
  skills: ["tutoring", "communication", "outdoor", "organization"],
  hoursLogged: 32,
  streakWeeks: 6,
};

export const categories: CategoryProgress[] = [
  {
    key: "community",
    label: "Community",
    logged: 12,
    goal: 15,
    tint: "lavender",
  },
  {
    key: "environment",
    label: "Environment",
    logged: 11,
    goal: 15,
    tint: "sky",
  },
  {
    key: "education",
    label: "Education",
    logged: 9,
    goal: 10,
    tint: "pink",
  },
];

export const shifts: Shift[] = [
  {
    id: "shift_riverside_cleanup",
    title: "Riverside Park Cleanup & Tree Planting",
    description:
      "Help restore Riverside Park trails, remove invasive plants, and plant native trees.",
    org: "City Parks Dept.",
    orgId: "org_city_parks",
    category: "Environment",
    categoryKey: "environment",
    categoryTint: "sky",
    date: "Sat, Jun 7 · 9:00 AM",
    scheduledAt: "2026-06-07T13:00:00.000Z",
    spotsLeft: 4,
    slots: 12,
    hours: 4,
    img: "https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=600&q=70",
    saved: true,
    skills: ["outdoor", "teamwork"],
    committed: false,
  },
  {
    id: "shift_food_bank",
    title: "Weekend Food Bank Sorting Shift",
    description:
      "Sort and pack food donations for families in need at Hope Community Kitchen.",
    org: "Hope Community Kitchen",
    orgId: "org_hope_kitchen",
    category: "Community",
    categoryKey: "community",
    categoryTint: "lavender",
    date: "Sun, Jun 8 · 1:00 PM",
    scheduledAt: "2026-06-08T17:00:00.000Z",
    spotsLeft: 9,
    slots: 15,
    hours: 3,
    img: "https://images.unsplash.com/photo-1593113598332-cd288d649433?w=600&q=70",
    saved: false,
    skills: ["organization", "communication"],
    committed: true,
  },
  {
    id: "shift_reading_buddies",
    title: "After-School Reading Buddies (Grades 1–3)",
    description:
      "Read aloud and help young students build literacy confidence.",
    org: "Lincoln Public Library",
    orgId: "org_lincoln_library",
    category: "Education",
    categoryKey: "education",
    categoryTint: "pink",
    date: "Mon, Jun 9 · 3:30 PM",
    scheduledAt: "2026-06-09T19:30:00.000Z",
    spotsLeft: 2,
    slots: 8,
    hours: 2,
    img: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=600&q=70",
    saved: false,
    skills: ["tutoring", "patience"],
    committed: false,
  },
  {
    id: "shift_senior_tech",
    title: "Senior Center Tech Help Drop-in",
    description:
      "Assist seniors with smartphones, tablets, and video calls with family.",
    org: "Maplewood Senior Center",
    orgId: "org_maplewood_senior",
    category: "Community",
    categoryKey: "community",
    categoryTint: "lavender",
    date: "Wed, Jun 11 · 4:00 PM",
    scheduledAt: "2026-06-11T20:00:00.000Z",
    spotsLeft: 6,
    slots: 10,
    hours: 2,
    img: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=600&q=70",
    saved: false,
    skills: ["technology", "communication"],
    committed: false,
  },
  {
    id: "shift_habitat_build",
    title: "Habitat Build Day — Framing Crew",
    description:
      "Join a supervised construction crew building affordable housing units.",
    org: "Habitat for Humanity",
    orgId: "org_habitat",
    category: "Community",
    categoryKey: "community",
    categoryTint: "lavender",
    date: "Sat, Jun 14 · 8:00 AM",
    scheduledAt: "2026-06-14T12:00:00.000Z",
    spotsLeft: 5,
    slots: 20,
    hours: 6,
    img: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=600&q=70",
    saved: false,
    skills: ["teamwork", "outdoor"],
    committed: false,
  },
  {
    id: "shift_green_coalition",
    title: "Community Garden Planting Day",
    description:
      "Plant vegetables and maintain raised beds at the Green City Coalition garden.",
    org: "Green City Coalition",
    orgId: "org_green_city",
    category: "Environment",
    categoryKey: "environment",
    categoryTint: "sky",
    date: "Sun, Jun 15 · 10:00 AM",
    scheduledAt: "2026-06-15T14:00:00.000Z",
    spotsLeft: 8,
    slots: 12,
    hours: 3,
    img: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&q=70",
    saved: true,
    skills: ["outdoor", "organization"],
    committed: false,
  },
  {
    id: "shift_math_tutoring",
    title: "Saturday Math Tutoring Lab",
    description:
      "Tutor middle school students in algebra and geometry prep sessions.",
    org: "Lincoln Public Library",
    orgId: "org_lincoln_library",
    category: "Education",
    categoryKey: "education",
    categoryTint: "pink",
    date: "Sat, Jun 21 · 9:00 AM",
    scheduledAt: "2026-06-21T13:00:00.000Z",
    spotsLeft: 3,
    slots: 6,
    hours: 3,
    img: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=600&q=70",
    saved: false,
    skills: ["tutoring", "communication"],
    committed: false,
  },
  {
    id: "shift_animal_shelter",
    title: "Animal Shelter Weekend Care",
    description:
      "Walk dogs, socialize cats, and help with shelter cleaning and enrichment.",
    org: "Paws & Hearts Rescue",
    orgId: "org_paws_hearts",
    category: "Community",
    categoryKey: "community",
    categoryTint: "lavender",
    date: "Sun, Jun 22 · 11:00 AM",
    scheduledAt: "2026-06-22T15:00:00.000Z",
    spotsLeft: 7,
    slots: 10,
    hours: 2,
    img: "https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=600&q=70",
    saved: false,
    skills: ["patience", "teamwork"],
    committed: false,
  },
];

export const committedShifts: string[] = ["shift_food_bank"];

export const hoursLog: ShiftLog[] = [
  {
    id: "log_hope_may31",
    shiftId: "shift_food_bank",
    org: "Hope Community Kitchen",
    date: "May 31, 2026",
    category: "Community",
    categoryKey: "community",
    categoryTint: "lavender",
    activity: "Served meals at the weekend shelter",
    hours: 4,
    status: "verified",
    avatar:
      "https://api.dicebear.com/9.x/shapes/svg?seed=Hope&backgroundColor=ECEAFB",
    qrToken: "kora.v1.mock_verified_hope",
    qrExpiresAt: null,
    verifiedAt: "2026-05-31T18:00:00.000Z",
    completedAt: "2026-05-31T17:00:00.000Z",
  },
  {
    id: "log_parks_may24",
    shiftId: "shift_riverside_cleanup",
    org: "City Parks Dept.",
    date: "May 24, 2026",
    category: "Environment",
    categoryKey: "environment",
    categoryTint: "sky",
    activity: "Trail restoration & invasive plant removal",
    hours: 3,
    status: "verified",
    avatar:
      "https://api.dicebear.com/9.x/shapes/svg?seed=Parks&backgroundColor=DDF0FB",
    qrToken: "kora.v1.mock_verified_parks",
    qrExpiresAt: null,
    verifiedAt: "2026-05-24T15:00:00.000Z",
    completedAt: "2026-05-24T14:00:00.000Z",
  },
  {
    id: "log_library_may20",
    shiftId: "shift_reading_buddies",
    org: "Lincoln Public Library",
    date: "May 20, 2026",
    category: "Education",
    categoryKey: "education",
    categoryTint: "pink",
    activity: "Tutored math for middle-schoolers",
    hours: 2,
    status: "pending",
    avatar:
      "https://api.dicebear.com/9.x/shapes/svg?seed=Library&backgroundColor=FBE4F1",
    qrToken: null,
    qrExpiresAt: null,
    verifiedAt: null,
    completedAt: "2026-05-20T17:30:00.000Z",
  },
  {
    id: "log_senior_may16",
    shiftId: "shift_senior_tech",
    org: "Maplewood Senior Center",
    date: "May 16, 2026",
    category: "Community",
    categoryKey: "community",
    categoryTint: "lavender",
    activity: "Helped residents with smartphones",
    hours: 2,
    status: "flagged",
    avatar:
      "https://api.dicebear.com/9.x/shapes/svg?seed=Senior&backgroundColor=ECEAFB",
    qrToken: "kora.v1.mock_flagged_senior",
    qrExpiresAt: null,
    verifiedAt: null,
    completedAt: "2026-05-16T18:00:00.000Z",
  },
  {
    id: "log_habitat_may10",
    shiftId: "shift_habitat_build",
    org: "Habitat for Humanity",
    date: "May 10, 2026",
    category: "Community",
    categoryKey: "community",
    categoryTint: "lavender",
    activity: "Framed exterior walls on Lot 14",
    hours: 6,
    status: "verified",
    avatar:
      "https://api.dicebear.com/9.x/shapes/svg?seed=Habitat&backgroundColor=ECEAFB",
    qrToken: "kora.v1.mock_verified_habitat",
    qrExpiresAt: null,
    verifiedAt: "2026-05-10T19:00:00.000Z",
    completedAt: "2026-05-10T18:00:00.000Z",
  },
  {
    id: "log_green_may3",
    shiftId: "shift_green_coalition",
    org: "Green City Coalition",
    date: "May 3, 2026",
    category: "Environment",
    categoryKey: "environment",
    categoryTint: "sky",
    activity: "Planted tomatoes and maintained compost bins",
    hours: 3,
    status: "verified",
    avatar:
      "https://api.dicebear.com/9.x/shapes/svg?seed=Green&backgroundColor=DDF0FB",
    qrToken: "kora.v1.mock_verified_green",
    qrExpiresAt: null,
    verifiedAt: "2026-05-03T16:00:00.000Z",
    completedAt: "2026-05-03T15:00:00.000Z",
  },
  {
    id: "log_math_apr26",
    shiftId: "shift_math_tutoring",
    org: "Lincoln Public Library",
    date: "Apr 26, 2026",
    category: "Education",
    categoryKey: "education",
    categoryTint: "pink",
    activity: "Algebra review session for 8th graders",
    hours: 3,
    status: "verified",
    avatar:
      "https://api.dicebear.com/9.x/shapes/svg?seed=Math&backgroundColor=FBE4F1",
    qrToken: "kora.v1.mock_verified_math",
    qrExpiresAt: null,
    verifiedAt: "2026-04-26T15:00:00.000Z",
    completedAt: "2026-04-26T14:00:00.000Z",
  },
  {
    id: "log_animal_apr19",
    shiftId: "shift_animal_shelter",
    org: "Paws & Hearts Rescue",
    date: "Apr 19, 2026",
    category: "Community",
    categoryKey: "community",
    categoryTint: "lavender",
    activity: "Dog walking and kennel cleaning",
    hours: 2,
    status: "verified",
    avatar:
      "https://api.dicebear.com/9.x/shapes/svg?seed=Paws&backgroundColor=ECEAFB",
    qrToken: "kora.v1.mock_verified_paws",
    qrExpiresAt: null,
    verifiedAt: "2026-04-19T16:00:00.000Z",
    completedAt: "2026-04-19T15:00:00.000Z",
  },
  {
    id: "log_parks_apr12",
    shiftId: "shift_riverside_cleanup",
    org: "City Parks Dept.",
    date: "Apr 12, 2026",
    category: "Environment",
    categoryKey: "environment",
    categoryTint: "sky",
    activity: "Mulched playground beds and picked up litter",
    hours: 2,
    status: "verified",
    avatar:
      "https://api.dicebear.com/9.x/shapes/svg?seed=Parks2&backgroundColor=DDF0FB",
    qrToken: "kora.v1.mock_verified_parks2",
    qrExpiresAt: null,
    verifiedAt: "2026-04-12T14:00:00.000Z",
    completedAt: "2026-04-12T13:00:00.000Z",
  },
  {
    id: "log_hope_apr5",
    shiftId: "shift_food_bank",
    org: "Hope Community Kitchen",
    date: "Apr 5, 2026",
    category: "Community",
    categoryKey: "community",
    categoryTint: "lavender",
    activity: "Sorted pantry donations and packed meal kits",
    hours: 3,
    status: "pending",
    avatar:
      "https://api.dicebear.com/9.x/shapes/svg?seed=Hope2&backgroundColor=ECEAFB",
    qrToken: null,
    qrExpiresAt: null,
    verifiedAt: null,
    completedAt: "2026-04-05T16:00:00.000Z",
  },
  {
    id: "log_library_mar29",
    shiftId: "shift_reading_buddies",
    org: "Lincoln Public Library",
    date: "Mar 29, 2026",
    category: "Education",
    categoryKey: "education",
    categoryTint: "pink",
    activity: "Reading buddies session with 2nd graders",
    hours: 2,
    status: "verified",
    avatar:
      "https://api.dicebear.com/9.x/shapes/svg?seed=Library2&backgroundColor=FBE4F1",
    qrToken: "kora.v1.mock_verified_library2",
    qrExpiresAt: null,
    verifiedAt: "2026-03-29T16:30:00.000Z",
    completedAt: "2026-03-29T15:30:00.000Z",
  },
  {
    id: "log_senior_mar22",
    shiftId: "shift_senior_tech",
    org: "Maplewood Senior Center",
    date: "Mar 22, 2026",
    category: "Community",
    categoryKey: "community",
    categoryTint: "lavender",
    activity: "Set up video calls for residents",
    hours: 2,
    status: "flagged",
    avatar:
      "https://api.dicebear.com/9.x/shapes/svg?seed=Senior2&backgroundColor=ECEAFB",
    qrToken: null,
    qrExpiresAt: null,
    verifiedAt: null,
    completedAt: "2026-03-22T17:00:00.000Z",
  },
];

export const completedShiftLogs: ShiftLog[] = [
  {
    id: "log_library_may20",
    shiftId: "shift_reading_buddies",
    org: "Lincoln Public Library",
    date: "May 20, 2026",
    category: "Education",
    categoryKey: "education",
    categoryTint: "pink",
    activity: "Tutored math for middle-schoolers",
    hours: 2,
    status: "pending",
    avatar:
      "https://api.dicebear.com/9.x/shapes/svg?seed=Library&backgroundColor=FBE4F1",
    qrToken: null,
    qrExpiresAt: null,
    verifiedAt: null,
    completedAt: "2026-05-20T17:30:00.000Z",
  },
  {
    id: "log_hope_apr5",
    shiftId: "shift_food_bank",
    org: "Hope Community Kitchen",
    date: "Apr 5, 2026",
    category: "Community",
    categoryKey: "community",
    categoryTint: "lavender",
    activity: "Sorted pantry donations and packed meal kits",
    hours: 3,
    status: "pending",
    avatar:
      "https://api.dicebear.com/9.x/shapes/svg?seed=Hope2&backgroundColor=ECEAFB",
    qrToken: null,
    qrExpiresAt: null,
    verifiedAt: null,
    completedAt: "2026-04-05T16:00:00.000Z",
  },
  {
    id: "log_senior_mar22",
    shiftId: "shift_senior_tech",
    org: "Maplewood Senior Center",
    date: "Mar 22, 2026",
    category: "Community",
    categoryKey: "community",
    categoryTint: "lavender",
    activity: "Set up video calls for residents",
    hours: 2,
    status: "pending",
    avatar:
      "https://api.dicebear.com/9.x/shapes/svg?seed=Senior2&backgroundColor=ECEAFB",
    qrToken: null,
    qrExpiresAt: null,
    verifiedAt: null,
    completedAt: "2026-03-22T17:00:00.000Z",
  },
];

export const monthlyHours: MonthlyHours[] = [
  { label: "Feb", value: 4 },
  { label: "Mar", value: 7 },
  { label: "Apr", value: 6 },
  { label: "May", value: 11 },
  { label: "Jun", value: 4 },
];

export const organizations: Organization[] = [
  {
    id: "org_habitat",
    name: "Habitat for Humanity",
    description:
      "Build affordable housing with supervised construction crews open to student volunteers.",
    categories: ["community"],
    distance: "2.1 mi",
    verified: true,
    avatar:
      "https://api.dicebear.com/9.x/icons/svg?seed=Habitat&backgroundColor=ECEAFB",
    following: false,
    upcomingShifts: 2,
  },
  {
    id: "org_green_city",
    name: "Green City Coalition",
    description:
      "Environmental stewardship through community gardens, cleanups, and tree planting.",
    categories: ["environment"],
    distance: "0.8 mi",
    verified: true,
    avatar:
      "https://api.dicebear.com/9.x/icons/svg?seed=Green&backgroundColor=DDF0FB",
    following: false,
    upcomingShifts: 3,
  },
  {
    id: "org_lincoln_library",
    name: "Lincoln Public Library",
    description:
      "After-school tutoring, reading buddies, and literacy programs for K–12 students.",
    categories: ["education"],
    distance: "1.4 mi",
    verified: true,
    avatar:
      "https://api.dicebear.com/9.x/icons/svg?seed=LibraryOrg&backgroundColor=FBE4F1",
    following: true,
    upcomingShifts: 4,
  },
  {
    id: "org_hope_kitchen",
    name: "Hope Community Kitchen",
    description:
      "Meal service and food pantry operations serving families across the county.",
    categories: ["community"],
    distance: "1.9 mi",
    verified: true,
    avatar:
      "https://api.dicebear.com/9.x/icons/svg?seed=HopeOrg&backgroundColor=ECEAFB",
    following: false,
    upcomingShifts: 2,
  },
  {
    id: "org_city_parks",
    name: "City Parks Dept.",
    description:
      "Park maintenance, trail restoration, and environmental conservation projects.",
    categories: ["environment"],
    distance: "3.2 mi",
    verified: true,
    avatar:
      "https://api.dicebear.com/9.x/icons/svg?seed=ParksOrg&backgroundColor=DDF0FB",
    following: false,
    upcomingShifts: 1,
  },
  {
    id: "org_maplewood_senior",
    name: "Maplewood Senior Center",
    description:
      "Tech help, companionship visits, and activity support for senior residents.",
    categories: ["community"],
    distance: "2.5 mi",
    verified: true,
    avatar:
      "https://api.dicebear.com/9.x/icons/svg?seed=SeniorOrg&backgroundColor=ECEAFB",
    following: false,
    upcomingShifts: 1,
  },
  {
    id: "org_paws_hearts",
    name: "Paws & Hearts Rescue",
    description:
      "Animal care, adoption events, and shelter enrichment for rescued pets.",
    categories: ["community"],
    distance: "4.0 mi",
    verified: true,
    avatar:
      "https://api.dicebear.com/9.x/icons/svg?seed=PawsOrg&backgroundColor=ECEAFB",
    following: false,
    upcomingShifts: 2,
  },
  {
    id: "org_youth_mentors",
    name: "Youth Mentors Network",
    description:
      "One-on-one mentoring and group workshops for at-risk middle school students.",
    categories: ["education", "community"],
    distance: "1.1 mi",
    verified: true,
    avatar:
      "https://api.dicebear.com/9.x/icons/svg?seed=YouthOrg&backgroundColor=FBE4F1",
    following: false,
    upcomingShifts: 3,
  },
];

export const friends: Friend[] = [
  {
    id: "friend_jordan",
    name: "Jordan Park",
    role: "38 hrs logged",
    avatar:
      "https://api.dicebear.com/9.x/avataaars/svg?seed=Jordan&backgroundColor=DDF0FB",
  },
  {
    id: "friend_sofia",
    name: "Sofia Reyes",
    role: "41 hrs logged",
    avatar:
      "https://api.dicebear.com/9.x/avataaars/svg?seed=Sofia&backgroundColor=FBE4F1",
  },
  {
    id: "friend_devin",
    name: "Devin Walters",
    role: "29 hrs logged",
    avatar:
      "https://api.dicebear.com/9.x/avataaars/svg?seed=Devin&backgroundColor=ECEAFB",
  },
];

export const tints: Record<TintKey, { bg: string; fg: string }> = {
  lavender: { bg: "bg-accent-lavender", fg: "text-primary" },
  pink: { bg: "bg-accent-pink", fg: "text-icon-pink" },
  sky: { bg: "bg-accent-sky", fg: "text-icon-sky" },
};
