import type {
  AppNotification,
  CategoryProgress,
  Friend,
  MonthlyHours,
  OrgModerator,
  Organization,
  Shift,
  ConversationThread,
  ShiftLog,
  StudentProfile,
  TintKey,
} from "@/lib/types/student";

export type { CategoryKey, LogStatus, TintKey } from "@/lib/types/student";

export const student: StudentProfile = {
  id: "user_maya_chen",
  name: "Maya Chen",
  firstName: "Maya",
  grade: "11th Grade · Lincoln High",
  avatar:
    "https://api.dicebear.com/9.x/avataaars/svg?seed=Maya&backgroundColor=ECEAFB",
  schoolId: "school_lincoln_high",
  schoolState: "FL",
  skills: ["tutoring", "communication", "outdoor", "organization"],
  hoursLogged: 32,
  streakWeeks: 6,
};

export const orgModerators: OrgModerator[] = [
  {
    id: "mod_parks",
    name: "Elena Vasquez",
    avatar:
      "https://api.dicebear.com/9.x/avataaars/svg?seed=Elena&backgroundColor=DDF0FB",
    roleTitle: "Parks Volunteer Coordinator",
    totalVerifications: 214,
  },
  {
    id: "mod_hope",
    name: "Marcus Webb",
    avatar:
      "https://api.dicebear.com/9.x/avataaars/svg?seed=Marcus&backgroundColor=ECEAFB",
    roleTitle: "Kitchen Operations Lead",
    totalVerifications: 387,
  },
  {
    id: "mod_library",
    name: "Priya Nair",
    avatar:
      "https://api.dicebear.com/9.x/avataaars/svg?seed=Priya&backgroundColor=FBE4F1",
    roleTitle: "Youth Programs Director",
    totalVerifications: 156,
  },
  {
    id: "mod_maplewood",
    name: "James Okonkwo",
    avatar:
      "https://api.dicebear.com/9.x/avataaars/svg?seed=James&backgroundColor=ECEAFB",
    roleTitle: "Community Engagement Manager",
    totalVerifications: 92,
  },
  {
    id: "mod_habitat",
    name: "Rachel Kim",
    avatar:
      "https://api.dicebear.com/9.x/avataaars/svg?seed=Rachel&backgroundColor=ECEAFB",
    roleTitle: "Site Supervisor",
    totalVerifications: 278,
  },
  {
    id: "mod_green",
    name: "Tomás Herrera",
    avatar:
      "https://api.dicebear.com/9.x/avataaars/svg?seed=Tomas&backgroundColor=DDF0FB",
    roleTitle: "Garden Program Lead",
    totalVerifications: 143,
  },
  {
    id: "mod_paws",
    name: "Avery Collins",
    avatar:
      "https://api.dicebear.com/9.x/avataaars/svg?seed=Avery&backgroundColor=ECEAFB",
    roleTitle: "Shelter Volunteer Manager",
    totalVerifications: 201,
  },
  {
    id: "mod_youth",
    name: "Danielle Brooks",
    avatar:
      "https://api.dicebear.com/9.x/avataaars/svg?seed=Danielle&backgroundColor=FBE4F1",
    roleTitle: "Mentorship Coordinator",
    totalVerifications: 118,
  },
];

const moderatorById = new Map(orgModerators.map((m) => [m.id, m]));

export const orgModeratorIds: Record<string, string> = {
  org_habitat: "mod_habitat",
  org_green_city: "mod_green",
  org_lincoln_library: "mod_library",
  org_hope_kitchen: "mod_hope",
  org_city_parks: "mod_parks",
  org_maplewood_senior: "mod_maplewood",
  org_paws_hearts: "mod_paws",
  org_youth_mentors: "mod_youth",
};

export function getModeratorById(id: string): OrgModerator | undefined {
  return moderatorById.get(id);
}

export function getModeratorForOrg(orgId: string): OrgModerator | undefined {
  const moderatorId = orgModeratorIds[orgId];
  return moderatorId ? moderatorById.get(moderatorId) : undefined;
}

export const categories: CategoryProgress[] = [
  {
    key: "community",
    label: "Community",
    logged: 12,
    goal: 15,
    tint: "lavender",
  },
  {
    key: "environment",
    label: "Environment",
    logged: 11,
    goal: 15,
    tint: "sky",
  },
  {
    key: "education",
    label: "Education",
    logged: 9,
    goal: 10,
    tint: "pink",
  },
];

export const shifts: Shift[] = [
  {
    id: "shift_riverside_cleanup",
    title: "Riverside Park Cleanup & Tree Planting",
    description:
      "Help restore Riverside Park trails, remove invasive plants, and plant native trees.",
    org: "City Parks Dept.",
    orgId: "org_city_parks",
    moderatorId: "mod_parks",
    category: "Environment",
    categoryKey: "environment",
    categoryTint: "sky",
    date: "Sat, Jun 7 · 9:00 AM",
    scheduledAt: "2026-06-07T13:00:00.000Z",
    spotsLeft: 4,
    slots: 12,
    hours: 4,
    img: "https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=600&q=70",
    location: "Riverside Park, 1200 River Rd",
    whatToBring: ["Closed-toe shoes", "Water bottle", "Sun hat"],
    saved: true,
    skills: ["outdoor", "teamwork"],
    committed: false,
  },
  {
    id: "shift_food_bank",
    title: "Weekend Food Bank Sorting Shift",
    description:
      "Sort and pack food donations for families in need at Hope Community Kitchen.",
    org: "Hope Community Kitchen",
    orgId: "org_hope_kitchen",
    moderatorId: "mod_hope",
    category: "Community",
    categoryKey: "community",
    categoryTint: "lavender",
    date: "Sun, Jun 8 · 1:00 PM",
    scheduledAt: "2026-06-08T17:00:00.000Z",
    spotsLeft: 9,
    slots: 15,
    hours: 3,
    img: "https://images.unsplash.com/photo-1593113598332-cd288d649433?w=600&q=70",
    location: "Hope Community Kitchen, 450 Oak St",
    whatToBring: ["Hair tie", "Comfortable clothes"],
    saved: false,
    skills: ["organization", "communication"],
    committed: true,
  },
  {
    id: "shift_reading_buddies",
    title: "After-School Reading Buddies (Grades 1–3)",
    description:
      "Read aloud and help young students build literacy confidence.",
    org: "Lincoln Public Library",
    orgId: "org_lincoln_library",
    moderatorId: "mod_library",
    category: "Education",
    categoryKey: "education",
    categoryTint: "pink",
    date: "Mon, Jun 9 · 3:30 PM",
    scheduledAt: "2026-06-09T19:30:00.000Z",
    spotsLeft: 2,
    slots: 8,
    hours: 2,
    img: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=600&q=70",
    location: "Lincoln Public Library, 200 Main St",
    whatToBring: ["Photo ID", "Notebook"],
    saved: false,
    skills: ["tutoring", "patience"],
    committed: false,
  },
  {
    id: "shift_senior_tech",
    title: "Senior Center Tech Help Drop-in",
    description:
      "Assist seniors with smartphones, tablets, and video calls with family.",
    org: "Maplewood Senior Center",
    orgId: "org_maplewood_senior",
    moderatorId: "mod_maplewood",
    category: "Community",
    categoryKey: "community",
    categoryTint: "lavender",
    date: "Wed, Jun 11 · 4:00 PM",
    scheduledAt: "2026-06-11T20:00:00.000Z",
    spotsLeft: 6,
    slots: 10,
    hours: 2,
    img: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=600&q=70",
    location: "Maplewood Senior Center, 88 Elm Ave",
    whatToBring: ["Laptop or tablet (optional)"],
    saved: false,
    skills: ["technology", "communication"],
    committed: false,
  },
  {
    id: "shift_habitat_build",
    title: "Habitat Build Day — Framing Crew",
    description:
      "Join a supervised construction crew building affordable housing units.",
    org: "Habitat for Humanity",
    orgId: "org_habitat",
    moderatorId: "mod_habitat",
    category: "Community",
    categoryKey: "community",
    categoryTint: "lavender",
    date: "Sat, Jun 14 · 8:00 AM",
    scheduledAt: "2026-06-14T12:00:00.000Z",
    spotsLeft: 5,
    slots: 20,
    hours: 6,
    img: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=600&q=70",
    location: "Habitat Build Site, 900 Cedar Ln",
    whatToBring: ["Work gloves", "Closed-toe boots", "Water bottle"],
    saved: false,
    skills: ["teamwork", "outdoor"],
    committed: false,
  },
  {
    id: "shift_green_coalition",
    title: "Community Garden Planting Day",
    description:
      "Plant vegetables and maintain raised beds at the Green City Coalition garden.",
    org: "Green City Coalition",
    orgId: "org_green_city",
    moderatorId: "mod_green",
    category: "Environment",
    categoryKey: "environment",
    categoryTint: "sky",
    date: "Sun, Jun 15 · 10:00 AM",
    scheduledAt: "2026-06-15T14:00:00.000Z",
    spotsLeft: 8,
    slots: 12,
    hours: 3,
    img: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&q=70",
    location: "Green City Coalition Garden, 55 Vine St",
    whatToBring: ["Gardening gloves", "Sunscreen"],
    saved: true,
    skills: ["outdoor", "organization"],
    committed: false,
  },
  {
    id: "shift_math_tutoring",
    title: "Saturday Math Tutoring Lab",
    description:
      "Tutor middle school students in algebra and geometry prep sessions.",
    org: "Lincoln Public Library",
    orgId: "org_lincoln_library",
    moderatorId: "mod_library",
    category: "Education",
    categoryKey: "education",
    categoryTint: "pink",
    date: "Sat, Jun 21 · 9:00 AM",
    scheduledAt: "2026-06-21T13:00:00.000Z",
    spotsLeft: 3,
    slots: 6,
    hours: 3,
    img: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=600&q=70",
    location: "Lincoln Public Library, 200 Main St",
    whatToBring: ["Calculator", "Scratch paper"],
    saved: false,
    skills: ["tutoring", "communication"],
    committed: false,
  },
  {
    id: "shift_animal_shelter",
    title: "Animal Shelter Weekend Care",
    description:
      "Walk dogs, socialize cats, and help with shelter cleaning and enrichment.",
    org: "Paws & Hearts Rescue",
    orgId: "org_paws_hearts",
    moderatorId: "mod_paws",
    category: "Community",
    categoryKey: "community",
    categoryTint: "lavender",
    date: "Sun, Jun 22 · 11:00 AM",
    scheduledAt: "2026-06-22T15:00:00.000Z",
    spotsLeft: 7,
    slots: 10,
    hours: 2,
    img: "https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=600&q=70",
    location: "Paws & Hearts Rescue, 310 Pawprint Way",
    whatToBring: ["Closed-toe shoes", "Old clothes"],
    saved: false,
    skills: ["patience", "teamwork"],
    committed: false,
  },
];

export const committedShifts: string[] = [
  "shift_food_bank",
  "shift_riverside_cleanup",
];

export const hoursLog: ShiftLog[] = [
  {
    id: "log_hope_may31",
    shiftId: "shift_food_bank",
    org: "Hope Community Kitchen",
    date: "May 31, 2026",
    category: "Community",
    categoryKey: "community",
    categoryTint: "lavender",
    activity: "Served meals at the weekend shelter",
    hours: 4,
    status: "verified",
    avatar:
      "https://api.dicebear.com/9.x/shapes/svg?seed=Hope&backgroundColor=ECEAFB",
    qrToken: "kora.v1.mock_verified_hope",
    qrExpiresAt: null,
    verifiedAt: "2026-05-31T18:00:00.000Z",
    verifiedByModeratorId: "mod_hope",
    completedAt: "2026-05-31T17:00:00.000Z",
  },
  {
    id: "log_parks_may24",
    shiftId: "shift_riverside_cleanup",
    org: "City Parks Dept.",
    date: "May 24, 2026",
    category: "Environment",
    categoryKey: "environment",
    categoryTint: "sky",
    activity: "Trail restoration & invasive plant removal",
    hours: 3,
    status: "verified",
    avatar:
      "https://api.dicebear.com/9.x/shapes/svg?seed=Parks&backgroundColor=DDF0FB",
    qrToken: "kora.v1.mock_verified_parks",
    qrExpiresAt: null,
    verifiedAt: "2026-05-24T15:00:00.000Z",
    verifiedByModeratorId: "mod_parks",
    completedAt: "2026-05-24T14:00:00.000Z",
  },
  {
    id: "log_riverside_pending",
    shiftId: "shift_riverside_cleanup",
    org: "City Parks Dept.",
    date: "Jun 7, 2026",
    category: "Environment",
    categoryKey: "environment",
    categoryTint: "sky",
    activity: "Riverside Park Cleanup & Tree Planting",
    hours: 4,
    status: "pending",
    avatar:
      "https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=600&q=70",
    qrToken: null,
    qrExpiresAt: null,
    verifiedAt: null,
    completedAt: "2026-06-07T17:00:00.000Z",
  },
  {
    id: "log_library_may20",
    shiftId: "shift_reading_buddies",
    org: "Lincoln Public Library",
    date: "May 20, 2026",
    category: "Education",
    categoryKey: "education",
    categoryTint: "pink",
    activity: "Tutored math for middle-schoolers",
    hours: 2,
    status: "pending",
    avatar:
      "https://api.dicebear.com/9.x/shapes/svg?seed=Library&backgroundColor=FBE4F1",
    qrToken: null,
    qrExpiresAt: null,
    verifiedAt: null,
    completedAt: "2026-05-20T17:30:00.000Z",
  },
  {
    id: "log_senior_may16",
    shiftId: "shift_senior_tech",
    org: "Maplewood Senior Center",
    date: "May 16, 2026",
    category: "Community",
    categoryKey: "community",
    categoryTint: "lavender",
    activity: "Helped residents with smartphones",
    hours: 2,
    status: "flagged",
    avatar:
      "https://api.dicebear.com/9.x/shapes/svg?seed=Senior&backgroundColor=ECEAFB",
    qrToken: "kora.v1.mock_flagged_senior",
    qrExpiresAt: null,
    verifiedAt: null,
    flagReason:
      "Hours matched 3 other students within 10 minutes — flagged for counselor review per school policy.",
    completedAt: "2026-05-16T18:00:00.000Z",
  },
  {
    id: "log_habitat_may10",
    shiftId: "shift_habitat_build",
    org: "Habitat for Humanity",
    date: "May 10, 2026",
    category: "Community",
    categoryKey: "community",
    categoryTint: "lavender",
    activity: "Framed exterior walls on Lot 14",
    hours: 6,
    status: "verified",
    avatar:
      "https://api.dicebear.com/9.x/shapes/svg?seed=Habitat&backgroundColor=ECEAFB",
    qrToken: "kora.v1.mock_verified_habitat",
    qrExpiresAt: null,
    verifiedAt: "2026-05-10T19:00:00.000Z",
    completedAt: "2026-05-10T18:00:00.000Z",
  },
  {
    id: "log_green_may3",
    shiftId: "shift_green_coalition",
    org: "Green City Coalition",
    date: "May 3, 2026",
    category: "Environment",
    categoryKey: "environment",
    categoryTint: "sky",
    activity: "Planted tomatoes and maintained compost bins",
    hours: 3,
    status: "verified",
    avatar:
      "https://api.dicebear.com/9.x/shapes/svg?seed=Green&backgroundColor=DDF0FB",
    qrToken: "kora.v1.mock_verified_green",
    qrExpiresAt: null,
    verifiedAt: "2026-05-03T16:00:00.000Z",
    completedAt: "2026-05-03T15:00:00.000Z",
  },
  {
    id: "log_math_apr26",
    shiftId: "shift_math_tutoring",
    org: "Lincoln Public Library",
    date: "Apr 26, 2026",
    category: "Education",
    categoryKey: "education",
    categoryTint: "pink",
    activity: "Algebra review session for 8th graders",
    hours: 3,
    status: "verified",
    avatar:
      "https://api.dicebear.com/9.x/shapes/svg?seed=Math&backgroundColor=FBE4F1",
    qrToken: "kora.v1.mock_verified_math",
    qrExpiresAt: null,
    verifiedAt: "2026-04-26T15:00:00.000Z",
    completedAt: "2026-04-26T14:00:00.000Z",
  },
  {
    id: "log_animal_apr19",
    shiftId: "shift_animal_shelter",
    org: "Paws & Hearts Rescue",
    date: "Apr 19, 2026",
    category: "Community",
    categoryKey: "community",
    categoryTint: "lavender",
    activity: "Dog walking and kennel cleaning",
    hours: 2,
    status: "verified",
    avatar:
      "https://api.dicebear.com/9.x/shapes/svg?seed=Paws&backgroundColor=ECEAFB",
    qrToken: "kora.v1.mock_verified_paws",
    qrExpiresAt: null,
    verifiedAt: "2026-04-19T16:00:00.000Z",
    completedAt: "2026-04-19T15:00:00.000Z",
  },
  {
    id: "log_parks_apr12",
    shiftId: "shift_riverside_cleanup",
    org: "City Parks Dept.",
    date: "Apr 12, 2026",
    category: "Environment",
    categoryKey: "environment",
    categoryTint: "sky",
    activity: "Mulched playground beds and picked up litter",
    hours: 2,
    status: "verified",
    avatar:
      "https://api.dicebear.com/9.x/shapes/svg?seed=Parks2&backgroundColor=DDF0FB",
    qrToken: "kora.v1.mock_verified_parks2",
    qrExpiresAt: null,
    verifiedAt: "2026-04-12T14:00:00.000Z",
    completedAt: "2026-04-12T13:00:00.000Z",
  },
  {
    id: "log_hope_apr5",
    shiftId: "shift_food_bank",
    org: "Hope Community Kitchen",
    date: "Apr 5, 2026",
    category: "Community",
    categoryKey: "community",
    categoryTint: "lavender",
    activity: "Sorted pantry donations and packed meal kits",
    hours: 3,
    status: "pending",
    avatar:
      "https://api.dicebear.com/9.x/shapes/svg?seed=Hope2&backgroundColor=ECEAFB",
    qrToken: null,
    qrExpiresAt: null,
    verifiedAt: null,
    completedAt: "2026-04-05T16:00:00.000Z",
  },
  {
    id: "log_library_mar29",
    shiftId: "shift_reading_buddies",
    org: "Lincoln Public Library",
    date: "Mar 29, 2026",
    category: "Education",
    categoryKey: "education",
    categoryTint: "pink",
    activity: "Reading buddies session with 2nd graders",
    hours: 2,
    status: "verified",
    avatar:
      "https://api.dicebear.com/9.x/shapes/svg?seed=Library2&backgroundColor=FBE4F1",
    qrToken: "kora.v1.mock_verified_library2",
    qrExpiresAt: null,
    verifiedAt: "2026-03-29T16:30:00.000Z",
    completedAt: "2026-03-29T15:30:00.000Z",
  },
  {
    id: "log_senior_mar22",
    shiftId: "shift_senior_tech",
    org: "Maplewood Senior Center",
    date: "Mar 22, 2026",
    category: "Community",
    categoryKey: "community",
    categoryTint: "lavender",
    activity: "Set up video calls for residents",
    hours: 2,
    status: "flagged",
    avatar:
      "https://api.dicebear.com/9.x/shapes/svg?seed=Senior2&backgroundColor=ECEAFB",
    qrToken: null,
    qrExpiresAt: null,
    verifiedAt: null,
    flagReason:
      "Duplicate entry detected for the same shift window. Contact your counselor to resolve.",
    completedAt: "2026-03-22T17:00:00.000Z",
  },
];

export const completedShiftLogs: ShiftLog[] = [
  {
    id: "log_library_may20",
    shiftId: "shift_reading_buddies",
    org: "Lincoln Public Library",
    date: "May 20, 2026",
    category: "Education",
    categoryKey: "education",
    categoryTint: "pink",
    activity: "Tutored math for middle-schoolers",
    hours: 2,
    status: "pending",
    avatar:
      "https://api.dicebear.com/9.x/shapes/svg?seed=Library&backgroundColor=FBE4F1",
    qrToken: null,
    qrExpiresAt: null,
    verifiedAt: null,
    completedAt: "2026-05-20T17:30:00.000Z",
  },
  {
    id: "log_hope_apr5",
    shiftId: "shift_food_bank",
    org: "Hope Community Kitchen",
    date: "Apr 5, 2026",
    category: "Community",
    categoryKey: "community",
    categoryTint: "lavender",
    activity: "Sorted pantry donations and packed meal kits",
    hours: 3,
    status: "pending",
    avatar:
      "https://api.dicebear.com/9.x/shapes/svg?seed=Hope2&backgroundColor=ECEAFB",
    qrToken: null,
    qrExpiresAt: null,
    verifiedAt: null,
    completedAt: "2026-04-05T16:00:00.000Z",
  },
  {
    id: "log_senior_mar22",
    shiftId: "shift_senior_tech",
    org: "Maplewood Senior Center",
    date: "Mar 22, 2026",
    category: "Community",
    categoryKey: "community",
    categoryTint: "lavender",
    activity: "Set up video calls for residents",
    hours: 2,
    status: "pending",
    avatar:
      "https://api.dicebear.com/9.x/shapes/svg?seed=Senior2&backgroundColor=ECEAFB",
    qrToken: null,
    qrExpiresAt: null,
    verifiedAt: null,
    completedAt: "2026-03-22T17:00:00.000Z",
  },
];

export const monthlyHours: MonthlyHours[] = [
  { label: "Feb", value: 4 },
  { label: "Mar", value: 7 },
  { label: "Apr", value: 6 },
  { label: "May", value: 11 },
  { label: "Jun", value: 4 },
];

export const organizations: Organization[] = [
  {
    id: "org_habitat",
    name: "Habitat for Humanity",
    description:
      "Build affordable housing with supervised construction crews open to student volunteers.",
    categories: ["community"],
    distance: "2.1 mi",
    verified: true,
    avatar:
      "https://api.dicebear.com/9.x/icons/svg?seed=Habitat&backgroundColor=ECEAFB",
    following: false,
    upcomingShifts: 2,
    moderatorId: "mod_habitat",
  },
  {
    id: "org_green_city",
    name: "Green City Coalition",
    description:
      "Environmental stewardship through community gardens, cleanups, and tree planting.",
    categories: ["environment"],
    distance: "0.8 mi",
    verified: true,
    avatar:
      "https://api.dicebear.com/9.x/icons/svg?seed=Green&backgroundColor=DDF0FB",
    following: false,
    upcomingShifts: 3,
    moderatorId: "mod_green",
  },
  {
    id: "org_lincoln_library",
    name: "Lincoln Public Library",
    description:
      "After-school tutoring, reading buddies, and literacy programs for K–12 students.",
    categories: ["education"],
    distance: "1.4 mi",
    verified: true,
    avatar:
      "https://api.dicebear.com/9.x/icons/svg?seed=LibraryOrg&backgroundColor=FBE4F1",
    following: true,
    upcomingShifts: 4,
    moderatorId: "mod_library",
  },
  {
    id: "org_hope_kitchen",
    name: "Hope Community Kitchen",
    description:
      "Meal service and food pantry operations serving families across the county.",
    categories: ["community"],
    distance: "1.9 mi",
    verified: true,
    avatar:
      "https://api.dicebear.com/9.x/icons/svg?seed=HopeOrg&backgroundColor=ECEAFB",
    following: false,
    upcomingShifts: 2,
    moderatorId: "mod_hope",
  },
  {
    id: "org_city_parks",
    name: "City Parks Dept.",
    description:
      "Park maintenance, trail restoration, and environmental conservation projects.",
    categories: ["environment"],
    distance: "3.2 mi",
    verified: true,
    avatar:
      "https://api.dicebear.com/9.x/icons/svg?seed=ParksOrg&backgroundColor=DDF0FB",
    following: false,
    upcomingShifts: 1,
    moderatorId: "mod_parks",
  },
  {
    id: "org_maplewood_senior",
    name: "Maplewood Senior Center",
    description:
      "Tech help, companionship visits, and activity support for senior residents.",
    categories: ["community"],
    distance: "2.5 mi",
    verified: true,
    avatar:
      "https://api.dicebear.com/9.x/icons/svg?seed=SeniorOrg&backgroundColor=ECEAFB",
    following: false,
    upcomingShifts: 1,
    moderatorId: "mod_maplewood",
  },
  {
    id: "org_paws_hearts",
    name: "Paws & Hearts Rescue",
    description:
      "Animal care, adoption events, and shelter enrichment for rescued pets.",
    categories: ["community"],
    distance: "4.0 mi",
    verified: true,
    avatar:
      "https://api.dicebear.com/9.x/icons/svg?seed=PawsOrg&backgroundColor=ECEAFB",
    following: false,
    upcomingShifts: 2,
    moderatorId: "mod_paws",
  },
  {
    id: "org_youth_mentors",
    name: "Youth Mentors Network",
    description:
      "One-on-one mentoring and group workshops for at-risk middle school students.",
    categories: ["education", "community"],
    distance: "1.1 mi",
    verified: true,
    avatar:
      "https://api.dicebear.com/9.x/icons/svg?seed=YouthOrg&backgroundColor=FBE4F1",
    following: false,
    upcomingShifts: 3,
    moderatorId: "mod_youth",
  },
];

export const friends: Friend[] = [
  {
    id: "friend_jordan",
    name: "Jordan Park",
    role: "38 hrs logged",
    avatar:
      "https://api.dicebear.com/9.x/avataaars/svg?seed=Jordan&backgroundColor=DDF0FB",
  },
  {
    id: "friend_sofia",
    name: "Sofia Reyes",
    role: "41 hrs logged",
    avatar:
      "https://api.dicebear.com/9.x/avataaars/svg?seed=Sofia&backgroundColor=FBE4F1",
  },
  {
    id: "friend_devin",
    name: "Devin Walters",
    role: "29 hrs logged",
    avatar:
      "https://api.dicebear.com/9.x/avataaars/svg?seed=Devin&backgroundColor=ECEAFB",
  },
];

export const messageTemplates = [
  "I missed the QR scan, please manually verify my hours",
  "I have a question about this shift",
] as const;

export const conversationThreads: ConversationThread[] = [
  {
    id: "thread_friend_jordan",
    kind: "friend",
    pinned: false,
    unread: true,
    contactId: "friend_jordan",
    contactName: "Jordan Park",
    contactAvatar:
      "https://api.dicebear.com/9.x/avataaars/svg?seed=Jordan&backgroundColor=DDF0FB",
    contactSubtitle: "38 hrs logged",
    messages: [
      {
        id: "msg_jordan_1",
        sender: "friend",
        body: "Are you doing the food bank shift this weekend?",
        sentAt: "2026-06-05T19:10:00.000Z",
      },
      {
        id: "msg_jordan_2",
        sender: "student",
        body: "Yes — I committed yesterday!",
        sentAt: "2026-06-05T19:24:00.000Z",
      },
      {
        id: "msg_jordan_3",
        sender: "friend",
        body: "Nice, see you there!",
        sentAt: "2026-06-05T20:01:00.000Z",
      },
    ],
    updatedAt: "2026-06-05T20:01:00.000Z",
  },
  {
    id: "thread_food_bank",
    kind: "moderator",
    pinned: false,
    unread: false,
    contactId: "mod_hope",
    contactName: "Marcus Webb",
    contactAvatar:
      "https://api.dicebear.com/9.x/avataaars/svg?seed=Marcus&backgroundColor=ECEAFB",
    contactSubtitle: "Kitchen Operations Lead",
    shiftId: "shift_food_bank",
    shiftTitle: "Weekend Food Bank Sorting Shift",
    shiftDate: "Sun, Jun 8 · 1:00 PM",
    messages: [
      {
        id: "msg_food_bank_1",
        sender: "moderator",
        body: "Thanks for committing to this shift. Check-in code will be displayed at the end.",
        sentAt: "2026-06-05T14:10:00.000Z",
      },
      {
        id: "msg_food_bank_2",
        sender: "student",
        body: "I missed the QR scan, please manually verify my hours",
        sentAt: "2026-06-08T20:15:00.000Z",
      },
      {
        id: "msg_food_bank_3",
        sender: "moderator",
        body: "Got it — I’ll review your check-in and update your hours shortly.",
        sentAt: "2026-06-08T20:42:00.000Z",
      },
    ],
    updatedAt: "2026-06-08T20:42:00.000Z",
  },
  {
    id: "thread_friend_sofia",
    kind: "friend",
    pinned: false,
    unread: true,
    contactId: "friend_sofia",
    contactName: "Sofia Reyes",
    contactAvatar:
      "https://api.dicebear.com/9.x/avataaars/svg?seed=Sofia&backgroundColor=FBE4F1",
    contactSubtitle: "41 hrs logged",
    messages: [
      {
        id: "msg_sofia_1",
        sender: "friend",
        body: "Did you finish your Bright Futures paperwork yet?",
        sentAt: "2026-06-04T15:30:00.000Z",
      },
    ],
    updatedAt: "2026-06-04T15:30:00.000Z",
  },
  {
    id: "thread_reading_buddies",
    kind: "moderator",
    pinned: false,
    unread: true,
    contactId: "mod_library",
    contactName: "Priya Nair",
    contactAvatar:
      "https://api.dicebear.com/9.x/avataaars/svg?seed=Priya&backgroundColor=FBE4F1",
    contactSubtitle: "Youth Programs Director",
    shiftId: "shift_reading_buddies",
    shiftTitle: "After-School Reading Buddies (Grades 1–3)",
    shiftDate: "Mon, Jun 9 · 3:30 PM",
    messages: [
      {
        id: "msg_reading_1",
        sender: "student",
        body: "I have a question about this shift",
        sentAt: "2026-06-07T16:05:00.000Z",
      },
      {
        id: "msg_reading_2",
        sender: "moderator",
        body: "Happy to help — what would you like to know?",
        sentAt: "2026-06-07T16:18:00.000Z",
      },
      {
        id: "msg_reading_3",
        sender: "student",
        body: "Do I need to bring anything for the reading session?",
        sentAt: "2026-06-07T16:22:00.000Z",
      },
      {
        id: "msg_reading_4",
        sender: "moderator",
        body: "Just yourself. We provide all books and materials at the front desk.",
        sentAt: "2026-06-07T16:30:00.000Z",
      },
    ],
    updatedAt: "2026-06-07T16:30:00.000Z",
  },
  {
    id: "thread_riverside_cleanup",
    kind: "moderator",
    pinned: false,
    unread: true,
    contactId: "mod_parks",
    contactName: "Elena Vasquez",
    contactAvatar:
      "https://api.dicebear.com/9.x/avataaars/svg?seed=Elena&backgroundColor=DDF0FB",
    contactSubtitle: "Parks Volunteer Coordinator",
    shiftId: "shift_riverside_cleanup",
    shiftTitle: "Riverside Park Cleanup & Tree Planting",
    shiftDate: "Sat, Jun 7 · 9:00 AM",
    messages: [
      {
        id: "msg_parks_1",
        sender: "moderator",
        body: "Reminder: wear closed-toe shoes and bring a water bottle.",
        sentAt: "2026-06-06T18:00:00.000Z",
      },
    ],
    updatedAt: "2026-06-06T18:00:00.000Z",
  },
];

export const appNotifications: AppNotification[] = [
  {
    id: "notif_hours_hope_jun8",
    kind: "hours_verified",
    title: "Hours verified",
    body: "Marcus Webb approved 3 hrs for Weekend Food Bank Sorting Shift at Hope Community Kitchen.",
    read: false,
    createdAt: "2026-06-08T21:05:00.000Z",
    href: "/hours/log_hope_may31",
  },
  {
    id: "notif_motivation_bright_futures",
    kind: "motivation",
    title: "Bright Futures progress",
    body: "You're so close to Bright Futures Silver — 43 hours to go. Keep it up!",
    read: false,
    createdAt: "2026-06-07T09:00:00.000Z",
    href: "/goals",
  },
  {
    id: "notif_hours_parks_may24",
    kind: "hours_verified",
    title: "Hours verified",
    body: "Elena Vasquez approved 3 hrs for Riverside Park Cleanup at City Parks Dept.",
    read: true,
    createdAt: "2026-05-24T16:00:00.000Z",
    href: "/hours/log_parks_may24",
  },
  {
    id: "notif_motivation_graduation",
    kind: "motivation",
    title: "Graduation requirement",
    body: "You're so close to your graduation service requirement — just 8 hours to go!",
    read: false,
    createdAt: "2026-06-05T08:30:00.000Z",
    href: "/goals",
  },
  {
    id: "notif_milestone_streak",
    kind: "milestone",
    title: "6-week streak",
    body: "Nice work — you've logged service hours 6 weeks in a row. Don't break the chain!",
    read: true,
    createdAt: "2026-06-03T12:00:00.000Z",
    href: "/",
  },
];

export const tints: Record<TintKey, { bg: string; fg: string }> = {
  lavender: { bg: "bg-accent-lavender", fg: "text-primary" },
  pink: { bg: "bg-accent-pink", fg: "text-icon-pink" },
  sky: { bg: "bg-accent-sky", fg: "text-icon-sky" },
};
